setter/urls.py
from django.urls import path

from . import views

app_name = 'setter'

urlpatterns = [
    # path('', views.dashboard, name='dashboard'),
    path('', views.assignments, name='dashboard'),

    # Assignments base and selected pages
    path('all_assignments/', views.assignments, name='assignments'),
    path('show_assignment/<int:pk>', views.assignments, name='assignment-id'),

    # Assignment add, rename and delete pages
    path('add_assignment/', views.add_assignment, name='add-assignment'),
    path('rename_assignment/<int:pk>', views.rename_assignment, name='rename-assignment'),
    path('delete_assignment/<int:pk>', views.soft_delete_assignment, name='delete-assignment'),
    path('restore_last_deleted_assignment/', views.restore_assignment, name='restore-assignment'),

    # Question add, edit and delete pages
    path('add_question/<int:pk>', views.add_question, name='add-question'),
    path('edit_question/<int:pk>', views.edit_question, name='edit-question'),
    path('delete_question/<int:pk>', views.delete_question, name='delete-question'),

]

ta_grader/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('setter.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setter/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

from .soft_deletion import SoftDeletionModel

class Assignment(SoftDeletionModel):
    title = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.title

    def set_title(self, title):
        self.title = title

    @classmethod
    def validation_error_message(self, e):

        error_message = e.messages[0]
        if "Ensure this value has" in error_message:
            return "Title must be at most 100 characters"
        elif error_message == "Assignment with this Title already exists.":
            return "Assignment with this title already exists"
        elif error_message == "This field cannot be blank.":
            return "Assignment title can not be blank"

        return "Unknown error :/"

class Question(SoftDeletionModel):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    tag_line = models.CharField(max_length=100)
    description = RichTextUploadingField()

    def __str__(self):
        return self.title

setter/forms.py
from django import forms

from .models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ['deleted_at']

        widgets = {
            'assignment': forms.Select(attrs = {"class": 'form-control'}),
            'title': forms.TextInput(attrs = {
                    "class": 'form-control',
                    'placeholder': 'Enter a title for the question...'
                }),
            'tag_line': forms.TextInput(attrs = {
                     "class": 'form-control',
                     'placeholder': 'Enter a brief one-liner about the question...'
                    }),
            'description': forms.Textarea(attrs = {
                    "class": 'form-control',
                    'placeholder': 'Describe the question in detail. Include images, tables, etc for clarity...'
                }),
        }

setter/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.conf import settings

from .models import Assignment, Question
from .forms import QuestionForm
from .tasks import schedule_hard_delete_assignment


def dashboard(request):
    context = {
        'title': "Dashboard",
        'nbar_link': "dashboard",
    }
    return render(request, "setter/dashboard.html", context)

def assignments(request, pk=None):
    """ Show all assignments is just a simpler version of show particular assignment.
    That is the only reason why pk and hence loading an assignment is optional."""

    if pk: # TODO: does key exist check
        assignment = Assignment.objects.get(id=pk)
        questions = assignment.question_set.all()
    else:
        assignment, questions = None, []

    all_assignments = Assignment.objects.all()

    context = {
        'title': "Assignments",
        'nbar_link': "assignments",
        'questions': questions,
        'all_assignments': all_assignments,
        'this_assignment': assignment,
    }
    return render(request, "setter/assignments.html", context)

def edit_question(request, pk):
    """pk here is a question id."""

    # TODO: does key exist check
    my_question = Question.objects.get(id=pk)
    assignment = my_question.assignment
    form = QuestionForm(instance=my_question)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=my_question)
        if form.is_valid():
            form.save()
            messages.success(request, "Edits made to the question have been saved")
            return redirect(reverse("setter:assignment-id", args=[assignment.id]))
        else:
            messages.error(request, "Errors need to be resolved")

    context = {
        'title': 'Question',
        'navbar_link': None,
        'form': form,
    }
    return render(request, "setter/question.html", context)

def add_question(request, pk):
    """pk here is an assignment id and NOT a question id."""

    assignment = Assignment.objects.get(id=pk)
    form = QuestionForm(initial={"assignment": assignment})

    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            assignment_id = request.POST.get('assignment')
            messages.success(request, "The question has been saved")
            return redirect(reverse("setter:assignment-id", args=[assignment_id]))
        else:
            messages.error(request, "Errors need to be resolved")

    context = {
        'title': 'Question',
        'navbar_link': None,
        'form': form,
    }
    return render(request, "setter/question.html", context)

def delete_question(request, pk):

    question = Question.objects.get(id=pk)
    question.delete()
    messages.success(request, "The question has been deleted")
    return redirect(request.META['HTTP_REFERER'])

def add_assignment(request):

    assignment_name = request.POST.get("assignment-name")
    assignment = Assignment(title=assignment_name)

    try:
        assignment.full_clean()
    except ValidationError as e:
        messages.error(request, Assignment.validation_error_message(e))
        return redirect(request.META['HTTP_REFERER'])

    assignment.save()
    messages.success(request, "The assignment has been added")

    return redirect(reverse("setter:assignment-id", args=[assignment.id]))

def rename_assignment(request, pk):

    assignment = Assignment.objects.get(id=pk)
    assignment_name = request.POST.get("assignment-name")
    assignment.set_title(assignment_name)

    try:
        assignment.full_clean()
    except ValidationError as e:
        messages.error(request, Assignment.validation_error_message(e))
        return redirect(request.META['HTTP_REFERER'])

    assignment.save()
    messages.success(request, "The assignment has been renamed")
    return redirect(request.META['HTTP_REFERER'])

def soft_delete_assignment(request, pk):

    assignment = Assignment.objects.get(id=pk)
    assignment.delete() # only soft deletion
    messages.success(request, "The assignment has been deleted")

    request.session['deleted_assg_pk'] = pk
    messages.add_message(request, settings.UNDO_MSSG_LEVEL, "Click to Undo")
    schedule_hard_delete_assignment(pk) # scheduled hard deletion

    return redirect(reverse("setter:assignments"))

def restore_assignment(request):

    pk = request.session['deleted_assg_pk']
    assignment = Assignment.all_objects.get(id=pk)
    assignment.restore()
    del request.session['deleted_assg_pk']

    return redirect(reverse("setter:assignments"))

setter/templates/setter/assignments.html
{% extends 'setter/base.html' %}

{% block css_content %}
{% load static %}
<link rel="stylesheet" href="{% static 'setter/css/assignments.css' %}">
{% endblock css_content %}

{% block content %}
<div class="row">

    <!------------------------------------------------- SIDEBAR ----------------------------------------------------->
    <!--------------------------------------------------------------------------------------------------------------->

    <div class="col-sm-4 bg-dark pt-2" id="sidebar">
        {% for assignment in all_assignments %}
        <div
            class="row
            {% if this_assignment == assignment %} active-bg-glow {% else %} hover-bg-glow mid-white-hover {% endif %} ">

            <!-- Assignment tile -->
            <a href="{% url 'setter:assignment-id' assignment.id %}" class="assignment-title-js py-2 col-md-10 px-2 fs-assignment-title text-start truncate
                {% if this_assignment == assignment %} max-white {% else %} mid-white-hover {% endif %}">
                <span class="ms-1">{{ assignment.title }}</span></a>

            <!-- Assignment tile edit button -->
            <a href="#rename-assignment-{{ assignment.id }}" data-bs-toggle="modal"
                data-bs-target="#rename-assignment-{{ assignment.id }}"
                class="rename-button-js col-md-2 d-flex justify-content-center align-items-center">
                <i
                    class="bi bi-pen rename-icon-js {% if this_assignment == assignment %} almost-max-white max-white-hover {% else %} mid-white-hover {% endif %}"></i></a>
        </div>

        <!-- Assignment title rename modal -->
        <div class="modal fade text-dark" id="rename-assignment-{{ assignment.id }}" tabindex="-1"
            aria-labelledby="rename-assignment-{{ assignment.id }}-label" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="rename-assignment-{{ assignment.id }}-label">Rename Assignment</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form role="form" method="POST" action="{% url 'setter:rename-assignment' assignment.id %}">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                <label class="control-label">Enter new name for the assignment '{{ assignment.title }}'
                                </label>
                                <input type="text" class="form-control input-lg" name="assignment-name"
                                    value="{{ assignment.title }}">
                            </div>
                            <div class="mt-3 text-end">
                                <button type="button" class="btn btn-secondary float-right"
                                    data-bs-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-primary">Rename assignment</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

        <!-- Arrow down -->
        {% if all_assignments|length == 0 %}
        <i class="bi bi-chevron-double-down text-white"></i>
        {% endif %}
    </div>

    <!-- Add and delete assignment buttons -->
    <div id="sidebar-buttons" class="bg-dark">
        <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#add-assignment">
            <span class="ms-1">Add Assignment</span>
        </a>
        <a href="#" class="btn btn-danger {% if this_assignment == None %} disabled {% endif %}" data-bs-toggle="modal"
            data-bs-target="#delete-assignment"> <span class=" ms-1">Delete Assignment</span>
        </a>
    </div>

    <!-- Add assignment modal -->
    <div class="modal fade" id="add-assignment" tabindex="-1" aria-labelledby="add-assignment-label" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="add-assignment-label">Add Assignment</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form role="form" method="POST" action="{% url 'setter:add-assignment' %}">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            <label class="control-label">Enter name of the assignment</label>
                            <input type="text" class="form-control input-lg" name="assignment-name" value="">
                        </div>
                        <div class="mt-3 text-end">
                            <button type="button" class="btn btn-secondary float-right"
                                data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Add assignment</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Delete assignment Modal -->
    <div class="modal fade" role="dialog" id="delete-assignment" tabindex="-1" aria-labelledby="delete-assignment-label"
        aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="delete-assignment-label">Delete Assignment</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">Are you sure you want to delete the assignment '{{ this_assignment.title }}'
                    and
                    all its
                    questions? </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="{% if this_assignment != None %} {% url 'setter:delete-assignment' this_assignment.id %} {% else%} # {% endif %}"
                        class="btn btn-danger button">Delete Assignment</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!------------------------------------------------- CONTENT ----------------------------------------------------->
<!--------------------------------------------------------------------------------------------------------------->

<div class="col-sm-4" id="questions">

    <!-- Messages -->
    {% include 'setter/messages.html' %}

    <!-- No assignments message -->
    {% if all_assignments|length == 0 %}
    <div id="empty-messages" class="p-2 fs-2 text-muted text-center">
        <p>NO ASSIGNMENTS YET</p>
    </div>
    {% endif %}

    <!-- No questions message -->
    {% if questions|length == 0 and this_assignment != None %}
    <div id="empty-messages" class="p-2 fs-2 text-muted text-center">
        <p>NO QUESTIONS YET</p>
    </div>
    {% endif %}

    <!-- No assignment selected message -->
    {% if questions|length == 0 and this_assignment == None and all_assignments|length != 0 %}
    <div id="empty-messages" class="p-2 fs-2 text-muted text-center">
        <p>NO ASSIGNMENT SELECTED </p>
    </div>
    {% endif %}

    <!-- Questions cards -->
    {% for question in questions %}
    <div class="card hover-border mt-3 mx-2">
        <div class="card-body">
            <h5 class="card-title">{{ question.title }}<a class="question-link stretched-link" href="#"
                    data-bs-toggle="modal" data-bs-target="#question-modal-{{ question.id }}"></a></h5>
            <p class="card-text">{{ question.tag_line }}</p>
        </div>
    </div>

    <!-- View questions modal -->
    <div class="modal fade" id="question-modal-{{ question.id }}" tabindex="-1"
        aria-labelledby="question-modal-{{ question.id }}-label" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header flex-wrap pb-2">
                    <h5 class="modal-title" id="question-modal-{{ question.id }}-label">{{ question.title }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

                    <!-- Line breaking from flex container -->
                    <div class="break"></div>
                    <p class="my-1">{{ question.tag_line }}</p>
                </div>
                <div class="modal-body py-0">
                    <p>{{ question.description|safe }}</p>
                </div>
                <div class="modal-footer">
                    <a href="{% url 'setter:edit-question' question.id %}" class="btn btn-primary button">Edit
                        Question</a>
                    <button type="button" class="btn btn-danger" data-bs-target="#delete-confirm-{{ question.id }}"
                        data-bs-toggle="modal" data-bs-dismiss="modal">Delete Question</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Delete question confirmation modal -->
    <div class="modal fade" id="delete-confirm-{{ question.id }}" aria-hidden="true"
        aria-labelledby="delete-confirm-{{ question.id }}-label" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="delete-confirm-{{ question.id }}-label">Delete Question Confirmation
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete the question '{{ question.title }}'?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="{% url 'setter:delete-question' question.id %}" class="btn btn-danger button">Confirm</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<!-- Rounded plus button -->
<!-- <a href="{% if this_assignment != None %}{% url 'setter:add-question' this_assignment.id %}{% else %}#{% endif %}"
    name="add-question" class="btn float-btn-plus {% if this_assignment == None %}disabled{% endif %}">
    <i class="bi bi-plus-circle-fill tooltip-test" title="Add question"></i>
</a> -->

<!-- Add question rounded pill button -->
{% if this_assignment != None %}
<a href="{% url 'setter:add-question' this_assignment.id %}" name="add-question"
    class="btn btn-primary btn-rounded float-btn-pill">
    Add question</a>
{% endif %}

</div>

{% endblock content %}

{% block js_content %}
<script src="{% static 'setter/js/assignments.js' %}"></script>
{% endblock js_content %}

setter/templates/setter/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Bootstrap-css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Bootstrap-icons cdn -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Document</title>
    {% endif %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'setter/css/base.css' %}">

    <!-- to include css -->
    {% block css_content %} {% endblock css_content %}

</head>

<body>

    <!-- Navbar -->
    {% include 'setter/navbar.html' %}

    <!-- Content -->
    {% block content %} {% endblock content %}

    <!-- Bootstrap JS bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- to include css -->
    {% block js_content %} {% endblock js_content %}
</body>

</html>

setter/templates/setter/dashboard.html
{% extends 'setter/base.html' %}

{% block content %}
{% include 'setter/messages.html' %}


{% endblock content %}

setter/templates/setter/messages.html
{% load static %}

{% block css_content %}
<link rel="stylesheet" href="{% static 'setter/css/messages.css' %}">
{% endblock css_content %}

<div id="message-container">
    {% for message in messages %}
    {% if message.tags != 'alert-undo' %}
    <div class="alert {{ message.tags }} alert-dismissible fade show mt-2 mb-0" role="alert">
        <button type="button" class="btn-close mssg-close-button" data-bs-dismiss="alert" aria-label="Close">
        </button>
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
</div>

{% for message in messages %}
{% if message.tags == 'alert-undo' %}
<div class="outer-container">
    <a href="{% url 'setter:restore-assignment' %}">
        <div class="undo-container">
            <div id="undo-assg-div" class="alert alert-dark alert-dismissible undo-assg-alert fade show mt-2 mb-0"
                role="alert">
                {{ message }}
            </div>
            <div class="progress" id="undo-assg-progress-div">
                <div class="progress-bar" id="undo-assg-progressbar" role="progressbar"></div>
            </div>
        </div>
    </a>
    <!-- outside the a-tag  -->
    <button type="button" class="btn-close" id="undo-assg-close-button" data-bs-dismiss="alert"
        aria-label="Close"></button>
</div>


{% endif %}
{% endfor %}

{% block js_content %}
<script src="{% static 'setter/js/messages.js' %}"></script>
{% endblock js_content %}

setter/templates/setter/navbar.html
{% load static %}

{% block css_content %}
<link rel="stylesheet" href="{% static 'setter/css/navbar.css' %}">
{% endblock css_content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid pe-3 ps-0">
        <a class="navbar-brand" href="#"><img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo image"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
                <!-- <a class="nav-link {% if nbar_link == 'dashboard' %}active{% endif %}"
                    href="{% url 'setter:dashboard' %}">Dashboard</a>
                <a class="nav-link {% if nbar_link == 'assignments' %}active{% endif %}"
                    href="{% url 'setter:assignments' %}">Assignments</a>
                <a class="nav-link {% if nbar_link == 'submissions' %}active{% endif %}" href="#">Submissions</a>
                <a class="nav-link {% if nbar_link == 'grade_report' %}active{% endif %}" href="#">Grade Report</a> -->
            </div>
        </div>
    </div>
</nav>

setter/templates/setter/question.html
{% extends 'setter/base.html' %}
{% load static %}

{% block css_content %}
<link rel="stylesheet" href="{% static 'setter/css/question.css' %}">
{% endblock css_content %}

{% block content %}

<!-- Messages -->
{% include 'setter/messages.html' %}

<div class="container mt-5">
    <div class="form-group">
        <form method="POST" action="#">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <a href="javascript:history.go(-1)" class="btn btn-danger me-1">Cancel</a>
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}